import Head from 'next/head';
import { Hero } from '../components/Hero';
import { ArrowTopRightOnSquareIcon } from '@heroicons/react/20/solid';
import { Footer } from '../components/Footer';
import { Cloud } from '../components/Cloud';
import { Stats } from '../components/Stats';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="./assets/favico.png" />
			</Head>

			<Hero />

			<div className="relative bg-gray-800">
				<div className="h-56 bg-indigo-600 sm:h-72 md:absolute md:left-0 md:h-full md:w-1/2">
					<img
						className="h-full w-full object-cover"
						src="https://images.unsplash.com/photo-1525130413817-d45c1d127c42?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1920&q=60&blend=6366F1&sat=-100&blend-mode=multiply"
						alt=""
					/>
				</div>
				<div className="relative mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16">
					<div className="md:ml-auto md:w-1/2 md:pl-10">
						{/* <h2 className="text-lg font-semibold text-gray-300">
							Award winning support
						</h2> */}
						<p className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
							Nous sommes là pour vous aider
						</p>
						<p className="mt-3 text-lg text-gray-300">
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et,
							egestas tempus tellus etiam sed. Quam a scelerisque amet
							ullamcorper eu enim et fermentum, augue. Aliquet amet volutpat
							quisque ut interdum tincidunt duis.
						</p>
						<div className="mt-8">
							<div className="inline-flex rounded-md shadow">
								<a
									href="#"
									className="inline-flex items-center justify-center rounded-md border border-transparent bg-white px-5 py-3 text-base font-medium text-gray-900 hover:bg-gray-50"
								>
									Voir le centre d&quote;aide
									<ArrowTopRightOnSquareIcon
										className="-mr-1 ml-3 h-5 w-5 text-gray-400"
										aria-hidden="true"
									/>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<Cloud />
			<Stats />
			<Footer />
		</div>
	);
}
